---
- hosts: all
  become: true
  
  tasks:
    - name: create test file
      copy:
        content: "Success!"
        dest: /Users/Administrator/Desktop/test.txt
        force: false
        mode: 0777
