---
- name: Execute remote command (using password vault)
  hosts: all
  become: true
  
  tasks:
    - name: Create text file with message
      file:
        path: home/pi/test.txt
        state: touch
        content: "Test Successful!"
        mode: 0644
  become: true

