---
- name: Execute remote command (using password vault)
  hosts: all
  tasks:
    - name: Create text file with message
      file:
        path: /tmp/test.txt
        state: present
        content: "Test Successful!"
        mode: 0644
  become: true

