---
- name: Execute remote command (using password vault)
  hosts: all
  become: true
  
  tasks:
    - name: Create text file with message
      copy:
        dest: home/pi/test.txt
        content: "Test Successful!"
        mode: 0644
  become: true

