---
- name: Transfer file from local to remote host
  hosts: all

  tasks:
    - name: Copy file from local to remote
      copy:
        src: /run/user/1000/gvfs/smb-share:server=100.97.54.44,share=installers/Youlean/Youlean-Loudness-Meter-2-V2.4.4-macOS.zip   # Replace with the actual path to your file
        dest: /Users/administrator/Desktop/ # Replace with the desired destination on the remote host
        mode: 0755  # Set permissions for the copied file (optional)
      register: copy_result

    - name: Debug copy result (optional)
      debug:
        msg: "File copied successfully: {{ copy_result.changed }}"
