---
- name: Download file from URL
  hosts: all  # Replace with specific hosts if needed
  become: true

  tasks:

    - name: Change to Downloads directory
      shell: cd /Users/administrator/Downloads && curl -o waves_central_macos.dmg https://cf-installers.waves.com
  
    #- name: Download Waves Download
    #  shell: curl -o waves_central_macos.dmg https://cf-installers.waves.com

    #- name: Debug the result (optional)
       # debug:
       # msg: "{{ file_check.stdout }}"
